default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

development:
  <<: *default
  database: jasonramirez_development
  host: localhost

test:
  <<: *default
  database: jasonramirez_test

production:
  <<: *default
  database: jasonramirez_production
